### ISSUE TITLE
lrt mediateka neveikia

### ISSUE THREAD

**Issue by gymka** [Vytax/plugin.video.lrt.lt#2]
lrt mediateka nerodo video

**Comment by zmogas** [comment]
Vytautai, reikia padidinti versiją ir supakuoti naujai zip'ą su mano pakeitimais. Tada visi, kas jau naudoja, atsinaujins ir vėl rodys mediateka. Aš pas save rankomis pasitaisiau, tai patenkintas žiūriu toliau :)

**Comment by TheSpy** [comment]
kaip padidinti versija?

**Comment by TheSpy** [comment]
man meta klaida kad cannot install due to invalid structure :(

**Comment by zmogas** [comment]
Na, autorius Vytax manau žino kaip padidinti versiją. Šiaip failus keisti čia gali tik autorius.
Kas bent kažkiek susigaudo pluginuose ir nori žiūrėti mediateka, atsikopinkit atnaujiną 'liblrt.py' ir viskas. :)

**Comment by modcptg** [comment]
Gal žinot kada bus sis pataisymas, kad per kodi updates galima būtų atnaujinti?

**Comment by gymka** [comment]
su atnaujintu liblrt.py veikia failai, bet vistiek neveikia paieška

**Comment by zmogas** [comment]
Kad ten sugriuvo, tai kalti LRT developeriai. Kad panaikino 'end' reikšmes. :) 
Dėl paieškos reiktų žiūrėti atidžiau kas ten dar blogai pasikeitė.

**Comment by Vytax** [comment]
Sveiki,
Pataisiau įskiepį. Problema kilo dėl pokyčių LRT puslapyje. Panaikintos video trukmės reikšmės. 
Atsiprašau, kad buvau neaktyvus. Buvau labai užimtas. Dabar įskiepis turėtų automatiškai atsinaujinti. 

Per atostogas galbūt pavyks įskiepį labiau patobulinti. 

Dėkui.

**Comment by TheSpy** [comment]
veikia! dekui! :)
