### ISSUE TITLE
lrt priedas neveikia

### ISSUE THREAD

**Issue by gymka** [Vytax/plugin.video.lrt.lt#3]
Net neatsidaro. kodi 17

**Comment by Vytax** [comment]
Sutvarkiau. 
Knygų mugės transliacijos nuorodą įdėjo nestandartiniu būdu. Skriptas nenuskaitė.

**Comment by gymka** [comment]
tu viską padarei kaip priklauso? :D man kodi nemato 0,5 versijos, tik 0,4... parsisiunčiau iš čia, viskas veikia, rodo v0,5...
EDIT: ok, nežinau wtf, bet db viskas ok ir kompe mato v0,5

**Comment by Vytax** [comment]
Gal konfliktuoja su kitomis repozitorijomis. 
Mano įskiepiai kažkokias būdais atsidūrė SuperRepo repozitorijoje. O ten ko gero vis dar sena įskiepio versija.
